language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy"
  - "pypy3"
  - "pypy-5.3.1"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - coverage run -m unittest discover

after_success:
  - coveralls
